### ISSUE TITLE
Práctica 2

### ISSUE THREAD

**Issue by ICervantes21** [ICervantes21/EstrD2023s1#14]
@FerRomMu

**Comment by FerRomMu** [comment]
Corregido.

**Comment by ICervantes21** [comment]
@FerRomMu apliqué varias correcciones

**Comment by FerRomMu** [comment]
Fijate que te corregí ya tus correcciones, te deje algunos comentarios en issues que cerre y otros en algunos que quedaron abiertos. Por otro lado, para saber en cuales aplicaste correcciones me fijé en tus commits, si me saltee alguno lo corrijo cuando tengas todos.

**Comment by ICervantes21** [comment]
@FerRomMu Hola! los commits ya estan todos, quedaron algunos issues que "creo" que los resolví

**Comment by FerRomMu** [comment]
Seguro? En agregarAlFinal por ejemplo no veo ningun cambio. Chequea que esten todos corregidos y avisame así miro todos de una.

**Comment by ICervantes21** [comment]
@FerRomMu Creo (y espero) que ya estan todas las correcciones

**Comment by FerRomMu** [comment]
Sisi esta vez se noto que los ejecutaste antes de pushearlo. Ahí te volví a corregir. Los que son respecto a la convención de como nombrar parámetros los podes cerrar vos mismo cuando los arregles porque no son errores, es una convención que hay que seguir.

**Comment by ICervantes21** [comment]
Ahi hice otro commit && push, perdoname que me había olvidado del de pokemon tambien

**Comment by FerRomMu** [comment]
Excelente! Liquidada la 2. Ahora me falta a mi corregirte la 3 jaja. En cuanto pueda lo hago. Excelente trabajo!
