### ISSUE TITLE
Pr.2: en agregarAlFinal no estás usando recursión estructural

### ISSUE THREAD

**Issue by FerRomMu** [ICervantes21/EstrD2023s1#15]
Si bien no está mal utilizar subtareas, esta es una práctica de recursión estructural, y la idea es que las puedan hacer con recursión estructural, en aquellos casos que se pueda (como este).

**Comment by ICervantes21** [comment]
@FerRomMu consulta, en agregarAlFinal si bien estoy utilizando "++" no aparece ninguna subtarea en el código.

**Comment by FerRomMu** [comment]
El operador "++" es concat que es básicamente una subtarea. Lo que Fidel se refiere con ese mensaje de issue es que no lo uses en este ejercicio en particular porque te permite evitar usar RE. Y la idea es que uses RE.
