### ISSUE TITLE
Pr.3: ramaMasLarga no usa RE

### ISSUE THREAD

**Issue by FerRomMu** [ICervantes21/EstrD2023s1#39]
Tiene muchos errores juntos y todo por efecto de no usar RE. Fijate por ejemplo que sizeT no te da la rama mas larga, si no la que mas nodos tiene.

**Comment by FerRomMu** [comment]
leaves te va a causar tambien que falle. Y la realidad es que si lo hicieras andar tampoco sería feliz porque no estas haciendo RE.

**Comment by FerRomMu** [comment]
Esto sigue aplicando: "Fijate por ejemplo que sizeT no te da la rama mas larga, si no la que mas nodos tiene." ¿Que cosa del caso recursivo ya te trae algo a lo que le podes ver el tamaño para ver quien es mas largo?

**Comment by ICervantes21** [comment]
Profe no logro este ejercicio. No se supone que si una rama tiene mas nodos que otra, tambien significa que tiene mas elementos? probablementa hay algo que no me quedo claro, pero no encuentro solución sin tener al menos una subtarea

**Comment by FerRomMu** [comment]
Bien. Por un lado:

"No se supone que si una rama tiene mas nodos que otra, tambien significa que tiene mas elementos?" 
Dependiendo de que entendes por elementos sí. Porque los nodos serían los "elementos" por lo tanto si tiene mas nodos tiene mas elementos. Pero yo te pido la rama mas larga, no la que tiene mas elementos.

Fijate que:
```
    1
  /    \
 2     3
```
Tiene la misma cantidad de nodos que:
```
    1
  /    
 2     
/
3 
```

Sin embargo la segunda es mas larga que la primera. Entendiendo esto capaz veas otra forma de hacer el if en tu solución que si te va a dar el resultado correcto usando los arboles y esa solución sería valida.

Ahora bien fíjate que tratar de encontrar esa solución "valida" te llevó a un error al romper el esquema. Porque algo simple como quedarte con el resultado mas largo se transformo en una tarea compleja que es determinar que arbol va a tener la rama mas larga para saber cual me voy a quedar usando funciones que no son parte de la abstracción del problema (como en este caso sizeT). 

Por eso desde un inicio lo que yo te proponía era no romper el esquema recursivo en lo mas minimo para encontrar la solución "fácil" casi automaticamente. Preguntate ¿Que te devuelve `laRamaMasLarga t1`y que te devuelve `laRamaMasLarga t2`?  ¿Que es lo que quiero de esos resultados? En este contexto, lo de la subtarea no me parece una mala idea dependiendo de que hagas.

Como sea acá hay dos caminos distintos. Por un lado, continuar con tu solución reemplazando sizeT por una función que determine verdaderamente cual arbol tiene la rama mas larga, o bien, ir por el camino de aferrarse al esquema al máximo y describir la solución pensando que representa cada cosa (¿Que me devuelve `laRamaMasLarga t1`? ¿Que `laRamaMasLarga t2`? ¿Que quiero conservar yo de esas dos cosas?`).

**Comment by FerRomMu** [comment]
Te dije que efectivamente elementos y cantidad de nodos estaba relacionados por lo que eran lo mismo en base a tu pregunta y te di una explicación de porque eso estaba mal para el problema. Me leíste? En caso de haberme leído, en que parte me dejaste de entender?

**Comment by ICervantes21** [comment]
Perdon fer no me entraba en la cabeza que el llamado a la misma función me llevaba por donde quería ir. Cada nodo al tener uno o mas nodos me perdi en las millones de posibilidades para analizar y ver que rama es mas larga. A pesar de leerte mi mente daba vueltas en eso, de nuevo, te pido disculpas. Creo que ya esta resuelto y probado

**Comment by FerRomMu** [comment]
No pasa nada. No pidas perdón. Estamos aprendiendo. A veces me cuesta distinguir los que intentan adivinar la respuesta para que les cierre el issue y los que estan tratando posta.

Volviendo al tema del issue la respuesta es correcta. Así que cierro issue.

Me parece válido igual hablar un poco al respecto para pasar en limpio el error y porque sucedió. Quizas te ayude a evitar el mismo error a futuro. 

Fíjate que partiste de `if sizeT t1 > sizeT t2` si no mal recuerdo. Eso estaba mal porque para obtener la mas larga deberías haber mirado la altura y no el tamaño (es decir `if heightT t1 > heightT t2` ). Y el error surgió porque hacer eso (fijarte que arbol hijo es mas alto que el otro) rompe el esquema de recursion estructural y te sacó de la abstracción del problema. Nunca nos interesó cual es el hijo mas alto o el de mayor tamaño porque lo que nos interesaba era cual era la parte recursiva mas larga (que es lo que hace tu solución ahora).

¿Como evito esto? Mantengo el esquema y la abstracción.

Es raro que tengamos que mirar a t1 o a t2. Lo que vamos a querer ver es la parte recursiva `laRamaMasLarga t1` la cual siempre la tenemos que ver como el resultado para el arbol t1 (es decir en este caso una lista con los elementos de la rama mas larga de t1).

Entonces pensando así yo digo las partes recursivas me traen la lista con las ramas mas largas. Que necesito? Y quedarme con la mas larga y agregarle x. Vos eso lo terminas haciendo con un if que ahora esta bien pero te evita abstracción que es lo que te llevó a romper el esquema. Dicho eso yo normalmente resuelvo con subtarea transformando mis palabras en subtarea (quedarme con la mas larga podría ser laMasLarga). A veces con subtarea no se puede y el if es necesario pero si lo puedo decir con palabras normalmente lo puedo transformar en subtarea.

Aplicando esta logica, escribo esquema y aplico subtarea:
```haskell
laRamasMasLargaAlternativa EmptyT = []
laRamasMasLargaAlternativa (NodeT x t1 t2) =
    x: laMasLarga (laRamasMasLargaAlternativa t1)
                              (laRamasMasLargaAlternativa t2)
```
Esta solución es igual que la tuya con la diferencia de que mantiene la abstracción y eso me asegura a no pisar el palito. Como sea ambas soluciones son válidas. Así que cierro. Buen trabajo y si tenes dudas las charlamos. Saludos!
